[package]
name = "bevy-jam-7"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
jam7 = { path = "crates/jam7", version = "0.1.0" }
game = { path = "crates/game", version = "0.1.0" }

[workspace]
members = ["crates/*"]

[workspace.dependencies]
bevy = "0.18"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
