[package]
name = "sys_magic"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true

sys_move = { path = "../move", version = "0.1.0" }
sys_combat = { path = "../combat", version = "0.1.0" }
utils = { path = "../../crates/utils", version = "0.1.0" }

[features]
default = []
dev = ["bevy/dev"]
