[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true, features=["tonemapping_luts", "zstd_rust"] }
bevy_enhanced_input.workspace = true
jam7 = { path = "../jam7", version = "0.1.0" }
utils = { path = "../utils", version = "0.1.0" }


[features]
default = []
dev = ["jam7/dev", "bevy/dev"]
